site_url: https://timothe-joubert.netlify.app/
logo_url: https://timothe-joubert.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: false

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
    # Generals info
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: siteName, widget: string, hint: 'Nom du site' }
          - {
              label: Site Description,
              name: siteDescription,
              widget: string,
              hint: 'Description du site dans les recherches Google',
            }
          - { label: 'Share Image', name: 'shareImage', widget: 'image', required: true, allow_multiple: false }
   ## Tags
  - label: 'Tag de projet'
    name: 'projectTag'
    files:
        - label: 'Tags'
          name: 'tags'
          file: 'content/site/tag.json'
          format: 'json'
          editor:
              preview: false
          fields:
              - { label: Tag , name: tag, widget: list, hint: 'Ajouter un tag', allow_add: true }
    ## About
  - label: 'À propos'
    name: 'about'
    folder: 'content/about'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
        - { label: 'Title', name: 'title', widget: 'string', required: true }
        - { label: 'Description', name: 'description', widget: 'text', required: false }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Project Category',
          name: 'category',
          widget: 'select',
          default: 'animals',
          options: [{ label: 'Animals', value: 'animals' }, { label: 'Food', value: 'food' }],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: false, allow_multiple: false }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
