site_url: https://timothe-joubert.netlify.app/
logo_url: https://timothe-joubert.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: false

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
    # Generals info
  - label: 'Site settings'
    name: 'siteSettings'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: siteName, widget: string, hint: 'Nom du site' }
          - {
              label: Site Description,
              name: siteDescription,
              widget: string,
              hint: 'Description du site dans les recherches Google',
            }
          - { label: 'Share Image', name: 'shareImage', widget: 'image', required: true, allow_multiple: false }
      -   label: 'Tags'
          name: 'tags'
          file: 'content/site/tags.json'
          format: 'json'
          editor:
              preview: false
          fields:
              -   label: Tags
                  name: tagList
                  widget: list
                  summary: '{{fields.tag}}'
                  hint: 'Ajouter des tags'
                  allow_add: true
                  field: { label: Tag, name: tag, widget: string }
      -   label: 'À propos'
          name: 'about'
          file: 'content/site/about.json'
          format: 'json'
          editor:
              preview: false
          fields:
            - { label: 'Title', name: 'title', widget: 'string', required: true }
            - { label: 'Description', name: 'description', widget: 'text', required: false }
  - name: 'projects'
    label: 'Projets'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: "Tags",
          name: "tags",
          widget: "relation",
          collection: "siteSettings",
          file: "tags",
          search_fields: [ "tags"],
          value_field: "tags.*.tagList.tag",
          display_fields: [ "tags.*.tagList.tag"],
          multiple: true
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'date', default: '', format: 'YYYY MM DD' }
      - { label: "Coup de coeur", name: "promote", widget: "boolean", default: false }
      - { label: "Nouveau", name: "new", widget: "boolean", default: false }
      - { label: 'Lien', name: 'link', widget: 'markdown', required: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', allow_multiple: false, required: true, }
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
